### ISSUE TITLE
Is there any way to override the content-type in a request?

### ISSUE THREAD

**Issue by harumph** [mandest/Nap#2]
I've been trying to make a post request with xml body, Nap serialized it correctly but it sets content-type to text/plain.

    var nap = new Nap(baseurl);
    nap.Config.Serialization = Nap.Configuration.RequestFormat.Xml;
    var response = nap.Post(url)
        .IncludeBody(xml)
        .Execute();

xml is of type XmlDocument and my request headers look like this:

    POST https://contoso.com:8000/api/card/017123456/receipt HTTP/1.1
    Content-Type: text/plain; charset=utf-8
    Host: contoso.com:8000
    Content-Length: 582
    Expect: 100-continue
    Connection: Keep-Alive

The body is correctly serialized xml.

Is there any way to override the Content-Type? I've tried using IncludeHeader method but that failed as expected.

EDIT:
I thought you could be failing over to a ToString() method on the object passed to the IncludeBody method and assigning it a text/plain Content-Type. Since I passed it an XmlDocument object, I would be seeing a nicely parsed xml anyway.

So I created a model of my data that XmlSerializer could parse, and a nicely formatted xml is still present in the request body, but the Content-Type is still text/plain. It seems to be a bug.

**Comment by mandest** [comment]
You're absolutely correct - content-type was not being set.  This has been remedied to use, in order:

`.IncludeHeader("content-type", "CUSTOM/TYPE")`
and fall back to the 
`Serializer.ContentType`
if no content type is manually set.

This is present in develop, and will be added to the nuget package shortly.

**Comment by harumph** [comment]
Ah thank you! I just started playing around with Nap today and I'm loving it. Beautifully simple library. :)

**Comment by harumph** [comment]
I just pulled an update an it works great, thank you.

**Comment by mandest** [comment]
Absolutely - good to hear it's working well now!
