### ISSUE TITLE
Post(Url) throwing a null reference exception

### ISSUE THREAD

**Issue by asmorger** [mandest/Nap#3]
I'm trying to pass a fully formed, valid URL into Nap and it's throwing a null reference on me.  Logging here for convince. Maybe it's because I'm passing in the query params instead of using the interface to generate them?

* Code:
  * `var output = await Nap.Nap.Lets.Post(targetUrl).ExecuteAsync<TEntity>()`
* Request Url:
  * `https://launchpad.37signals.com/authorization/token?type=web_server&client_id=<id>&redirect_uri=<uri>&client_secret=<secret>&code=<code>`

Note: the following works!
`var client = new HttpClient();`
`var response = await client.SendAsync(new HttpRequestMessage(HttpMethod.Post, targetUrl));`
`var responseBody = await response.Content.ReadAsStringAsync();`
`var output = JsonConvert.DeserializeObject<TEntity>(responseBody);`

**Comment by asmorger** [comment]
Interesting.  I think this is me flat out doing it wrong.  I'll keep what I've got and let's talk later.

**Comment by mandest** [comment]
Looking at the code, this is a valid issue for POST/PUT requests without `IncludeBody()` called. Will fix next time I am near a computer.

**Comment by mandest** [comment]
Just released a new version - this should be addressed in Nap 0.0.2.4

**Comment by mandest** [comment]
Can't duplicate this.  Closing.
